### ISSUE TITLE
[Suggestion] Support chat-sync (named-pipe) with external programs

### ISSUE THREAD

**Issue by aabluedragon** [clipmove/NotBlood#18]
Hello, I'm adding support for NotBlood in NukemNet (multiplayer launcher based on IRC).
StrikerTheHedgefox (Author of NetDuke32) and I added support to sync chat messages between NukemNet and the game executable in-game chat.
It would be nice if NotBlood had support for that as well.
For reference, you can see relevant NetDuke32's commits here:
https://voidpoint.io/StrikerTheHedgefox/eduke32-csrefactor/-/commits/netduke32_main
(see commits from fca85cae).

The implementation is actually pretty simple.
1. Game is launched (by NukemNet or another external program).
2. Game executable starts listening on named pipe (e.g `\\.\pipe\NetDuke32` in windows, and `/tmp/netduke32pipe` on unix).
3. The external program maintains client connection to the named pipe (with retries) for every game participant.
4. When the external program user receives/sends a message in it's own chat system, it forwards it to NotBlood with the following JSON format, appended with NULL ascii char (0x00 so you can split messages if they arrive concatenated)
```json
{
            "event":"message"|"join"|"leave",
            "user":"someNick",
            "text":"message text" // on join and leave events this property is ignored
}
```
apart from "message" event, there's also "leave"/"join" events ("text" property is ignored on these).
5. The game executabe, NotBlood only sends the following json on the named pipe:
```json
{
            "event":"message",
            "text":"message text"
}
```
If there's anything else needed for integration feel free to contact me.

**Comment by StrikerMan780** [comment]
The leave/join messages have nothing to do with in-game joining, they have to do with people leaving and joining your NukemNet lobby.

**Comment by StrikerMan780** [comment]
Yeah, I plan on doing that as well in NetDuke32, just haven't got around to it yet.

**Comment by StrikerMan780** [comment]
You'll also want to rename the pipe name to NotBlood instead of NetDuke32. (on Line 187 of chatpipe.cpp)
Another thing you'll want to do, is tweak your message colors to match blood palettes. (if it even supports using ^ for color codes like EDuke32, that is.)

**Comment by aabluedragon** [comment]
Tested locally, everything worked fine, except when messages arriving from NukemNet into NotBlood, there are some numbers in the messages. see screenshot:
![blud0004](https://user-images.githubusercontent.com/1431364/213166284-6f23eaff-d2b3-4512-a103-5c5b71d8d582.png)

Also, please rename your pipes to-
windows: `\\.\pipe\NotBlood`
unix: `/tmp/notbloodpipe`

**Comment by aabluedragon** [comment]
Is there a dev release somewhere?

**Comment by aabluedragon** [comment]
Works great, here are a few screenshots.
unix socket file listener is not yet implemented in NetDuke32, however NukemNet supports that already, so if it's added in NotBlood, NukemNet should be able to connect on socket files too.
![msg_from_nukemnet](https://user-images.githubusercontent.com/1431364/213295266-0782f490-22d6-4fbe-83a3-b1f4cbf62264.png)
![nn_left](https://user-images.githubusercontent.com/1431364/213295286-e94869c5-c79e-4bfa-8dcc-6335736c3c2d.png)
![nn_join](https://user-images.githubusercontent.com/1431364/213295278-ec40a581-051f-49ed-a1f4-836c6d433f83.png)
